from control_ablations.generic_targets.fixed_control_target import FixedControlTarget, NoLearningControlTarget
from control_ablations.generic_targets.oc_io import OCIO
from control_ablations.generic_targets.optimal_control import OptimalControlCollocation
from control_ablations.generic_targets.optimal_control_target import OptimalControlTarget, MPCOptimalControlTarget
